### ISSUE TITLE
Issue with registering colourmaps on Windows

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/scicm#14]
Speaking with a student using Python on Windows wanting to use Scicm on their machine. They were able to install and import scicm with no errors, but it appears as though the colourmaps are not being registered correctly, they all look like:
`scicm.C:\\Users\\user\\path\\to\\python\\cmapname`. Attached below is a screenshot of the error:
![image](https://github.com/MBravoS/scicm/assets/17759175/e7332d6c-b6e7-4a1f-9aaa-24af20c5f2a6)

Looking at our code for registering colourmaps below:
```
# List of all colour maps in scicm
cmaps=[c.split('/')[-1].split('.')[0] for c in sorted(glob(f'{data_path}/*.txt'))]
```
 it's because you are splitting filenames by '/', whereas Windows machines use \ or rather as a string literal: '\\' to separate directories in paths. I think there should be a base function in Python that handles path names independently of the OS you are using.

**Comment by AstroRobin** [comment]
Okay yes, so the solution is to use the os basename function to get the stem of the file path:
```
import os

cmaps = [os.path.basename(c).split('.')[0] for c in sorted(glob(f'{data_path}/*.txt'))]
```

or perhaps even neater is using `pathlibs`

```
from pathlib import Path

cmaps = [Path(c).stem for c in sorted(glob(f'{data_path}/*.txt'))]
```
which also removes file extensions at the same time.

Sidenote, when I test using both of these packages on my machine for a file path that contains '\\' separators, I doesn't appear to work, but it does work on a windows machine so the function itself is OS dependent.

**Comment by MBravoS** [comment]
That's interesting, as from what I'm reading it seems that _in theory_ Windows should handle both type of separators. I went a different route with the fix though, as `os` does know what type to use and it's exposed through `os.sep`. So in the [_windows_path_fix_ branch](https://github.com/MBravoS/scicm/tree/windows_path_fix) I made the following change:
```
from os import path, sep

cmaps=[c.split(sep)[-1].split('.')[0] for c in sorted(glob(f'{data_path}{sep}*.txt'))]
```
That works fine on my Linux machine, so it should also work with MacOS. Is the student still around to test this fix in Windows? If so, let me know if it works so we can move this to the master branch.

**Comment by AstroRobin** [comment]
They will have to install from the devel branch on github yes?

**Comment by MBravoS** [comment]
From the _windows_path_fix_ branch I mentioned and linked before. I'm halfway through my work on the CI on the _devel_ branch and didn't want to delay this fix until that's finished.

**Comment by AstroRobin** [comment]
Realised afterwards there was a separate branch. It's strange though because I can't use the @windows_path_fix extension when using pip to install from github? @devel works, but the 2D_cmaps also doesn't work...

Can you try to install these branches to test this?

**Comment by MBravoS** [comment]
That's weird, I haven't tried installing _2D_cmaps_ from GitHub, but earlier today I tested installing _windows_path_fix_ from GitHub and it worked (though it wasn't fast). What's the error that it's giving you?

**Comment by AstroRobin** [comment]
Error message:
```
>>> pip install git+https://github.com/MBravoS/splotch.git@windows_path_fix
Collecting git+https://github.com/MBravoS/splotch.git@windows_path_fix
  Cloning https://github.com/MBravoS/splotch.git (to revision windows_path_fix) to /private/var/folders/5k/ps7pc2p16fsgzqhfryy_xkc0p_v4ys/T/pip-req-build-l9vmat0z
  Running command git clone -q https://github.com/MBravoS/splotch.git /private/var/folders/5k/ps7pc2p16fsgzqhfryy_xkc0p_v4ys/T/pip-req-build-l9vmat0z
  WARNING: Did not find branch or tag 'windows_path_fix', assuming revision or ref.
  Running command git checkout -q windows_path_fix
  error: pathspec 'windows_path_fix' did not match any file(s) known to git
WARNING: Discarding git+https://github.com/MBravoS/splotch.git@windows_path_fix. Command errored out with exit status 1: git checkout -q windows_path_fix Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q windows_path_fix Check the logs for full command output.```

**Comment by MBravoS** [comment]
That's because you are trying to install _splotch_ and not _scicm_. 😉

**Comment by AstroRobin** [comment]
Okay, if muck up monday still existed, this would classify as one of the classics....

That said, I just realised I must have copied this from the scicm GitHub Readme, which still says splotch :O

**Comment by MBravoS** [comment]
Sad to hear that muck up Monday is no longer a thing. That said, you are right that we have the wrong repo url in the README, I fixed that in the _windows_path_fix_ branch. If the fix works in Windows I'll merge into _master_.

**Comment by AstroRobin** [comment]
Confirmed that it is now working.

**Comment by MBravoS** [comment]
Excellent! I pushed v1.0.4 to master and to PyPI.
